### ISSUE TITLE
<Yugoslavia> - <Prince Paul's Name>

### ISSUE THREAD

**Issue by Box-BoxBox** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#103]
### Hoi4 Version

v1.12.10.91F2

### DH Version (Current one is 1.0.2-hotfix-1)

1.0.2-hotfix-1

### Description

```bash
Prince Paul's Name is YUG_Prince_Paul_HoG
```

### Screenshots/Video

![YUG](https://user-images.githubusercontent.com/125704273/219804681-1f6af051-98bb-4fa5-9efd-c1fa395e081b.png)

**Comment by Darijus11** [comment]
Fixed in the upcoming patch
