### ISSUE TITLE
Any country - white square artifacts flickering on map in factory locations

### ISSUE THREAD

**Issue by Jakebob70** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#109]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

Avalanche V1.12.10.91F2

### DH Version (Current one is 1.0.3)

1.03

### Other Mods

removed all other mods, issue still exists

### Description

```bash
graphics artifact.  When moving or zooming the map, white flickering squares on factory locations.
```

### Reproduction steps

```bash
1. Start a game
2. Zoom in a little to show terrain detail
3. Scroll or zoom the map in and out.  White squares will flicker in specific locations on the map.  From what I can tell it appears to be factory locations.  It works even in the country selector screen.  Disappears when zoomed out far enough (far enough that Ireland and Crimea are on the same screen).

1080P resolution.  Radeon RX 5500 XT video card.
```

### Screenshots/Video

![20230219171021_1](https://user-images.githubusercontent.com/125835877/219981045-3002c688-450e-4e9c-a07f-0f21eccb4935.jpg)
the squares flicker rapidly, this is what the screenshot caught as I moved the map.  It seems to be related to factory locations on the map, reproduced with Germany, Italy, USA with and without additional mods (restarted the game from Steam each time).

**Comment by markobekko** [comment]
Lower DirectX version in the game launcher settings
