### ISSUE TITLE
ENG - London Graphical Issue

### ISSUE THREAD

**Issue by Polskers** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#112]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

Yes i was

### Hoi4 Version

1.12.10

### DH Version (Current one is 1.0.3)

1.0.3

### Other Mods

Music Mod

### Description

```bash
When scrolling across the map and looking at England, London has a white square over it that flickers on and off, obscuring London from view. Something must be missing graphically or there is a graphical issue somewhere causing this.
```

### Reproduction steps

```bash
Start the game as any nation, move around the map and look at London, there will be a white square that flickers over the city.
```

### Screenshots/Video

![Screenshot 2023-02-27 131211](https://user-images.githubusercontent.com/50228622/221660279-7b864b5a-0713-442e-943f-97de2b12daa8.jpg)

**Comment by SverigePranke** [comment]
Change your graphics from DirectX 11 to DirectX 9 in the launcher
