### ISSUE TITLE
All - Missing support company icons, unable to remove them

### ISSUE THREAD

**Issue by lilp123a** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#119]
### OS

Linux

### Any Expansions?

All of them

### Are you using Steam?

No i'm not

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.12.11

### DH Version (Current one is 1.0.3)

1.0.3

### Description

```bash
Across all nations, the icons for artillery, engineers, cavalry reconnaissance, signal field hospital, supply and maintenance support companies are missing.
Upon putting one of them in a division design (or if it's already there in a starting template), you are unable to then remove it.
```

### Screenshots/Video

![image](https://user-images.githubusercontent.com/118286912/232061282-65afbc9a-4515-4821-9b98-d505a57baa7b.png)

**Comment by Darijus11** [comment]
Are you using any other mods?

**Comment by lilp123a** [comment]
No.

**Comment by Darijus11** [comment]
Reinstall the mod

**Comment by lilp123a** [comment]
I redownloaded the mod but it didn't make any difference. Is the Paradox Mods version up to date? It says it's for version 1.12.10 but it runs on 1.12.11 and I've seen it said in the Discord that it works for the current version.

**Comment by Darijus11** [comment]
I've checked with the steam version that is also "outdated" but everything worked. I don't use paradox mods so I'm not sure.
This is the official version of our mod btw: https://mods.paradoxplaza.com/mods/58496/Any

**Comment by lilp123a** [comment]
After redownloading the mod, installing it from Paradox Mods and haivng a friend send me the Steam Workshop version of the mod, this problem still persisted. The checksum I'm getting is ac7f. I haven't encountered a strange issue such as this with any other mod; could be linked to me running the game on Linux.
