### ISSUE TITLE
CHI/NEA - Northeastern Army Stuff

### ISSUE THREAD

**Issue by HighMountainGuy** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#12]
### Hoi4 Version

V1.12.7

### DH Version

V1.0

### Description

```bash
After the Northeastern Army loses the Battle of Rehe during Operation Nekka (in 1933) there should be an event that annexes it into the Republic of China.
```

### Reasoning

>[Zhang Xueliang](https://en.wikipedia.org/wiki/Zhang_Xueliang) commanded this army after the assassination of his father. Prior to the [Mukden Incident](https://en.wikipedia.org/wiki/Mukden_Incident) it possessed 12 infantry brigades and 3 cavalry brigades (estimated at 179,505 troops) in [northeast China](https://en.wikipedia.org/wiki/Northeast_China), in addition to 12 infantry brigades, 2 cavalry brigades and 3 artillery brigades stationed in northern China.[1] This Chinese army was badly underarmed after the retreat from the northeast, following the Mukden Incident when most of the arsenals and their arms were seized by Japan. Many units were only equipped with handguns, grenades, and traditional Chinese swords. It defended Chinchow against the Japanese in 1931, and Jehol and Hebei against the Japanese [Operation Nekka](https://en.wikipedia.org/wiki/Operation_Nekka) in 1933. [Zhang Xueliang](https://en.wikipedia.org/wiki/Zhang_Xueliang) was relieved of command after the fall of Jehol, being replaced by General [He Yingqin](https://en.wikipedia.org/wiki/He_Yingqin).

Zhang Xueliang was relieved of command after the fall of Jehol, being replaced by General He Yingqin (a commander of the Nanjing Government). This would make sense because the passing of leadership to Chiang's de-facto 2nd in Command would turn it into a KMT administered region until the He-Umezu Agreement stuff where the Hebei-Chahar Political Council is founded.
![image](https://user-images.githubusercontent.com/71605887/209567912-4125c80d-ec9c-4cdc-9cb4-ce398820b8cc.png)

He Yingqin replaced [Zhang Xueliang](https://en.wikipedia.org/wiki/Zhang_Xueliang) as chairman of the Beijing Military Committee, which was the supreme organ in charge of the military forces of Northern China. He advocated no direct confrontation with the Japanese troops, and signed the [Tanggu Cease-Fire Accord](https://en.wikipedia.org/wiki/Tanggu_Truce) with General [Yasuji Okamura](https://en.wikipedia.org/wiki/Yasuji_Okamura), who was deputy chief of staff of [Kantogun](https://en.wikipedia.org/wiki/Kantogun) at that time.
![image](https://user-images.githubusercontent.com/71605887/209567947-b6eed3f3-ebaf-449b-b463-75fdd0b994d4.png)

### Additional context

N/A

**Comment by markobekko** [comment]
Like i said in the other comment i wouldn't touch this, i fear i'd break something, the entire thing is such a mess, i'd postpone it to when we remake it
