### ISSUE TITLE
<Germany England> - <shadow planes>

### ISSUE THREAD

**Issue by generalyann29** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#121]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

Yes i was

### Hoi4 Version

Latest

### DH Version (Current one is 1.0.3)

1.0.3

### Description

```bash
Upon the channel my planes can't fight English planes but got killed by them + the English planes doesn't appear
```

### Screenshots/Video

![IMG_20230426_005504](https://user-images.githubusercontent.com/131827127/234426141-69fa10e7-a8e4-4b46-b380-c012d77d9d5d.jpg)

### Savegame

[Uploading Ironman German Reich 9.zip…]()

**Comment by Darijus11** [comment]
Fixed in the 1.1 patch.
