### ISSUE TITLE
<German Reich> - <Crash after trying to continue game>

### ISSUE THREAD

**Issue by Thekopo** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#126]
### OS

Windows 11

### Any Expansions?

Death or Dishonor, Waking the Tiger

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

Yes i was

### Hoi4 Version

Avalanche 1.12.12.456f(a266)

### DH Version (Current one is 1.0.3)

1.0.4

### Other Mods

(Player Only) Faster Ship Building, Easybuff+, 50 Construction Slots, Unlimited Dockyards Per Line

### Description

```bash
When I try to enter my saved game , it crashes.
```

### Reproduction steps

```bash
1. On the launcher, click 'Play' (Continue just enters DH and crashes when the progress bar almost finishes)
2. Click on SinglePlayer
3. Select Continue / Load Game > Select it (InstaCrash)
4. Wait for the progress bar to load almost finishes, the clock pointer appears and then it crashes.
```

### Logs

I can provide a log if you need it, just tell me how to get to it

### Savegame

[GER_1936_04_01_14.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/11479945/GER_1936_04_01_14.zip)

**Comment by Darijus11** [comment]
Disable your mods and try again
