### ISSUE TITLE
<Germany> - <Update of older Ship Class Names>

### ISSUE THREAD

**Issue by SinVeb** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#127]
### Hoi4 Version

1.12.12

### DH Version (Current one is 1.0.3)

1.0.4

### Description

```bash
Uboats:
Change U-43-class to the U 81 Class

Destroyers:
Change S7-class to D1 Class
Change S114-class to S90 Class
Change V1-class to G101 Class
Change Zerstörer 1922 to Type 23

Light Cruisers: 
Change Gazelle-class to Schwalbe Class (Assuming "Unprotected Cruiser" as the type term)
Change Königsberg-class to Gazelle Class

Heavy Cruisers:
Change König Wilhelm Class to Irene Class  (Assuming "Protected Cruiser as the type term)

Battlecruisers:
Change Moltke Class to Von der Tann Class

Battleships:
Change Kaiser-class to Kaiser Freidrich III Class
Change König-class to Helgoland Class
Change Bayern-class to König Class
Change L 20a-class to Bayern Class
Change Wurtemburg-class to L 20a Class

Escort Carrier
Name the Seaplane Carrier the Stuttgart Class
Change Ausonia-class to Roon Class

Carriers:
Change Roon-class to Ausonia Class
```

### Reasoning

Uboat:
To match commissioning year and give a red thread as these U-Boats were the inspiration for WW2 U-Boats

Destroyers: (Hard to do, as Germany didn't build destroyers before 1934)
The D#-torpedo boats were the larger torpedoboats that closer match a destroyer class
The S90 was the actual class that defined the large ocean-going torpedoboats (of which S114 was a part of)
The G101s were the first operational destroyers in the Imperial Navy (originally built for Argentina), the V1s were still torpedoboats
The Type 23 were the largest version of german built torpedoboats to that point, while the Zerstörer Type 1934 were the first domestically built destroyers

Light Cruiser:
To match commissioning year and type term (assuming "Unprotected Cruiser")
The Gazelle Class was the first modern light cruiser, and matches the '00 commissioning year

Heavy Cruiser: 
To match the class type, commissioning year and type term (assuming "Protected Cruiser")

Battlecruisers:
To closer match the commissioning year and create a better lineage (Von der Tann was the first BC)

Battleships:
To match the actual class name
To match commissioning year, and due to the fact that the Helgoland matched the original "super-dreadnought" (british Orion Class) in armament and weight
Difficult to match, as Germany didn't build "fast battleships" with a top-speed of >24 kt, so closest to match commissioning year
To match commissioning year and provide a class that was actually built
To provide the design that would replace the Bayern Class

Escort Carriers:
To reflect that the only non-auxiliary seaplane carrier was named Stuttgart
To reflect that Roon was still planned to carry seaplanes

Carriers:
To reflect that a converted Ausonia was supposed to carry fighters, bombers and torpedo-bombers

### Additional context

Some cruisers and battleships doesn't exactly match the setup of type names in the mod, but I have matched it as close to possible

**Comment by Darijus11** [comment]
Will be fixed/reworked with naval designer in the future
