### ISSUE TITLE
<Germany> - <Game crashes in late 1940 a few seconds after loading the game>

### ISSUE THREAD

**Issue by Folk-git** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#128]
### OS

Windows 10

### Any Expansions?

Nothing

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

Avalanche v1.12.14

### DH Version (Current one is 1.0.3)

1.0.4 (current one)

### Other Mods

no other mods

### Description

```bash
Game crashes during september 1940, i played from 33 to 40 last night without any issues, now i loaded the save and game crashes after i start moving units or doing other minor things.
```

### Reproduction steps

```bash
1. On the launcher, click 'Play' - game loads fine
2. Click on SinglePlayer and look for the load files
3. Select Continue / Load Game > Select it  and loads without crashing
4. Starts playing, move some units and set frontlines
5. Game crashes, most of the times when i move units close to the swiss border (idk of its related, but it crashes other places as well)
```

### Logs

[error.log](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/11581946/error.log) - error log 03

[error.log](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/11581949/error.log) - error log 02

[error.log](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/11581950/error.log) - error log 01

### Savegame

[GER_1940_09_12_12.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/11581961/GER_1940_09_12_12.zip)

[GER_1940_09_12_1222.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/11581962/GER_1940_09_12_1222.zip)

Both are the same file, just tried saving again to see if error persists

**Comment by Folk-git** [comment]
[system.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/11581986/system.zip)

**Comment by Darijus11** [comment]
R u playing on Historical?

**Comment by Darijus11** [comment]
Since this is not selected
![image](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/assets/30055353/2b8a1e65-2a19-4ae7-a0fa-d4616406a597)

**Comment by Darijus11** [comment]
I've declared war on Netherlands, Belgium, moved my troops and no crash.
Can you check integrity of your files?

**Comment by Folk-git** [comment]
Yeah, i didnt check historical AI and it crashed after i played a bit, I'll try change settings or maybe antivirus blocking it?

**Comment by Folk-git** [comment]
another error
[error.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/11582623/error.zip)
