### ISSUE TITLE
<Nation(s) Affected> - <Summary of Bug>

### ISSUE THREAD

**Issue by Subtrik** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#13]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.12.4aefa

### DH Version

1.0

### Other Mods

German Division Icons, German Luftwaffen Aces, German March Collection, Modifier Icons, Player-Led Peace Confrences, Smooth Borders Plus, Songs of Our Darkest Hour - Official Music Submod,

### Description

```bash
so i loaded a save game and all my divisions had no army assigned, the whole army assigningning GUI was gone, and the theater GUI was gone too, my divisions were still there but i couldn't even move them and shortly after i unpaused the game crashed. the save games shortly after 39 were now "from another version" although i had played them on the same version.
```

### Screenshots/Video

![image](https://user-images.githubusercontent.com/121452988/209573060-3d93035f-d9ab-4d38-9c2f-adbcda632d62.png)
![image](https://user-images.githubusercontent.com/121452988/209573096-5555193a-b1e0-46d0-b8ed-9353fc3660de.png)
![image](https://user-images.githubusercontent.com/121452988/209573131-a45819c7-86ea-4504-842c-8986f498ef38.png)

### Savegame

[autosave_temp.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10304419/autosave_temp.zip)

**Comment by markobekko** [comment]
We know that this bug happened to some other players, but unfortunately we can't do anything since it's related to hoi4 and not us

**Comment by markobekko** [comment]
The only suggestion is to try not using other mods
