### ISSUE TITLE
<Germany> - <The "Reichsgau Watheland" is over 600 days long>

### ISSUE THREAD

**Issue by Melonentyp** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#131]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

Avalanche V1.12.14.50e7

### DH Version (Current one is 1.0.4-hotfix1)

1.0.4-hotfix1

### Description

```bash
If I want to select the "Reichsgau Wartheland" decision after defeating Poland, it takes over 600 days for the states to become cores
```

**Comment by SverigePranke** [comment]
This is working as intended
