### ISSUE TITLE
<Nation(s) Affected> - <Summary of In-game Crash>

### ISSUE THREAD

**Issue by trif014** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#140]
### OS

Windows 11

### Any Expansions?

Together for Victory, Death or Dishonor, Waking the Tiger, Man the Guns, La Résistance, Battle For The Bosporus, No Step Back

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.12.14

### DH Version (Current one is 1.0.4-hotfix1)

1.0.4-hotfix1

### Other Mods

State Transfer Tool | Songs of Our Darkest Hour

### Description

```bash
Game crashes with 3D Units on. 

Specs: Ryzen 5 5600x | RX 6950XT | 32GB Ram
```

### Reproduction steps

```bash
Turn 3D units on
```

### Logs

[hoi4_20230623_112636.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/11851606/hoi4_20230623_112636.zip)

### Savegame

[autosave.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/11851608/autosave.zip)

**Comment by Darijus11** [comment]
We've already identified the issue and fixed it. We will deploy the fix with 1.0.5 version. The 1.0.5 version will be deployed when ready. In the meantime, keep 3D units off.
