### ISSUE TITLE
<Soviet Union> - <Vasily Blyukher is supposed to be killed.>

### ISSUE THREAD

**Issue by augmentifyofficial** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#147]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.12.14

### DH Version (Current one is 1.0.4-hotfix1)

V1.0.5DEV

### Other Mods

FPS Map, Ultimate Tech Tree: Darkest Hour, STT, Player-Led Peace Conferences, Map Modes+

### Description

```bash
Field Marshal Vasily Blyukher is supposed to be killed in the great purges.
```

**Comment by SverigePranke** [comment]
Blyukher can be purged by taking the Send Frinovsky to the Far East decision, which is unlocked by the NKVD Order N00447 focus
