### ISSUE TITLE
<Germany> - <Can't send volunteers>

### ISSUE THREAD

**Issue by Lorinn076** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#153]
### OS

Windows 11

### Any Expansions?

Nothing

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.12.6

### DH Version (Current one is 1.0.4-hotfix1)

1.0.4-hotfix1

### Description

```bash
I can't send volunteers as Germany, so i can't help fascist spain in the spanish civil war.
```

**Comment by Darijus11** [comment]
Vanilla bug. Restart the game.
