### ISSUE TITLE
All Nations Affected - Research button wont show up

### ISSUE THREAD

**Issue by man-many-numbers** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#154]
### OS

Windows 11

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.13.6.7bda

### DH Version (Current one is 1.0.4-hotfix1)

1.0.5dev

### Other Mods

None

### Description

```bash
When i try to research infantry equipment, armour, or anything naval where it would say how long it will take and the research button are just gone. even after i complete focuses about the army or navy, unsubscribe and resubscribe to the mod, and uninstall then re-install the game
```

### Screenshots/Video

![Screenshot 2024-02-04 113547](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/assets/158839922/af1c5a42-a753-41c0-8af4-24cd40c841c1)
![Screenshot 2024-02-04 113556](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/assets/158839922/08dffc45-9d62-444c-8a0e-737430557fea)
![Screenshot 2024-02-04 113539](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/assets/158839922/6e6f56bf-27b5-42f7-a1c0-a5589e68a103)

### Savegame

[ENG_1933_01_01_12.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/14157582/ENG_1933_01_01_12.zip)

**Comment by generalisofficial** [comment]
You're playing on the wrong game version, revert to 1.12.14
