### ISSUE TITLE
<Italy> - <Focus "Piccola Roma" gives effect in wrong province>

### ISSUE THREAD

**Issue by andreones97** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#155]
### Hoi4 Version

Avalanche 1.12.14

### DH Version (Current one is 1.0.4-hotfix1)

1.0.5 dev

### Other Mods

Songs of Darkest Hour

### Description

```bash
Italian focus "Piccola Roma" it refers to investment in province of Eritrea. Instead, the focus gives bonus to Somali Banaadir province.
```

### Screenshots/Video

![WhatsApp Image 2024-03-14 at 10 57 34](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/assets/163404089/15d14f99-b957-4986-a1c9-047ad352f834)

**Comment by generalisofficial** [comment]
Fixed
