### ISSUE TITLE
<Nation(s) Affected> - <odd map>

### ISSUE THREAD

**Issue by zulmietek** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#157]
### OS

Windows 10

### Any Expansions?

No Step Back

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

boliviar v1.14.5.0917 (d40a)

### DH Version (Current one is 1.0.4-hotfix1)

idk how to check it

### Other Mods

none

### Description

```bash
when i turn the game on, map is very odd
```

### Reproduction steps

```bash
.
```

### Screenshots/Video

![20240515191113_1](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/assets/169930819/a91e59f1-d8c3-4660-9688-b3d75c3a2a64)

**Comment by Darijus11** [comment]
Go on the steampage of Darkest Hour and read what it says in the big red box.
