### ISSUE TITLE
The Entire Map is black 

### ISSUE THREAD

**Issue by gherter29** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#158]
### OS

Windows 11

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.14.3

### DH Version (Current one is 1.0.4-hotfix1)

DH V1.0.5DEV

### Other Mods

None

### Description

```bash
The entire map is just completely black
```

### Reproduction steps

```bash
1) Launch the mod 

2) select any country to see the map
```

### Screenshots/Video

![issue report](https://github.com/user-attachments/assets/9a21da0d-ff4b-41ff-869e-23a04d889995)

**Comment by NKVD304** [comment]
Downgrade the version to 1.12.x
