### ISSUE TITLE
LXI/HNN/GUZ - China Map Related Issues

### ISSUE THREAD

**Issue by HighMountainGuy** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#16]
### OS

Windows 10

### Any Expansions?

Together for Victory, Death or Dishonor, Waking the Tiger, Man the Guns, La Résistance, No Step Back

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

V1.12.7

### DH Version

V1.0

### Other Mods

X

### Description

```bash
The borders displayed for Guizhou are the contemporary, modern PRC administrative divisions and not what actually fell under it during the period of 1933.
```

### Reproduction steps

```bash
X
```

### Screenshots/Video

![image](https://user-images.githubusercontent.com/71605887/209577820-213b0730-0a0f-4ea2-9bcb-f31c5015227d.png)

![image](https://user-images.githubusercontent.com/71605887/209576595-9e15411a-f7ec-473a-aaf1-6e89136960dc.png)

**Comment by markobekko** [comment]
Do you have a better source than this? our mapper doesn't want to change states without having something more concrete, thank you for reporting all these bugs

**Comment by HighMountainGuy** [comment]
This is one of the best sources available for the region, if you want more detailed stuff I'll need to ask a few people I know. I can link you up sources 
https://www.youtube.com/watch?v=IVD-ZzFkOuU
Video made by a known Chinese Warlord Era mapper shows the same thing, Guizhou was a massively factionalized region and Wang Jialie was only recognized as the provincial ruler because his powerbase was the strongest of all, this all collapsed when the Kuomintang invaded and annexed the region during the Encirclement Campaigns & Long March around 1935

The salient is also referenced in this video
https://youtu.be/TFTf91Tt8eo?t=68
![image](https://user-images.githubusercontent.com/71605887/209586033-400c5cf3-be44-4543-b90c-317a641ded01.png)

However if you're still skeptical I'll try digging more out

**Comment by markobekko** [comment]
Thank you very much!

**Comment by HighMountainGuy** [comment]
Np
