### ISSUE TITLE
<Nation(s) Affected> - <Summary of In-game Crash>

### ISSUE THREAD

**Issue by Pawcio213** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#18]
### OS

Windows 10

### Any Expansions?

Together for Victory, Death or Dishonor, Waking the Tiger, Man the Guns, La Résistance, No Step Back, By Blood Alone

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

Newest so I guess 1.12.7

### DH Version

Steam v1.0

### Other Mods

none

### Description

```bash
Just started my first playthrough as Germany and encountered small problem
Game crashes on a certain date
Exactly one day after autosave - 2 June 1938
No idea what might be the cause
```

### Reproduction steps

```bash
Game just crashes even if I don't do anything
```

### Logs

[error.log](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10304705/error.log)

### Savegame

[GER_1938_06_01_02.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10304703/GER_1938_06_01_02.zip)

**Comment by markobekko** [comment]
Did you get the latest hotfix? if you have it, in the main menu it should say that you have version 1.0.0 hotfix-1

**Comment by Pawcio213** [comment]
> Did you get the latest hotfix? if you have it, in the main menu it should say that you have version 1.0.0 hotfix-1

Apparently no
How to get it if I am using Steam version?

**Comment by markobekko** [comment]
Try restarting steam, if it doesn't work subscribe to the mod again

**Comment by Pawcio213** [comment]
> Try restarting steam, if it doesn't work subscribe to the mod again

It fixed the problem, thank you
