### ISSUE TITLE
GER - Invasion of Poland Focus Suggestion

### ISSUE THREAD

**Issue by HighMountainGuy** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#19]
### Hoi4 Version

1.12.7

### DH Version

V1.0

### Description

```bash
The "Danzig or War" decision should be removed and replaced with "Operation Himmler/Konserve
```

### Reasoning

Historically Germany never directly declared war on Poland following a demand on territorial concessions and the only case where Germany tried to influence Poland territorially was in the 1938 Polish-German Non-Aggression Pact Renewal negotiations where Germany demanded a motorway through the Pomorze-Gdansk region and annexation of Danzig as a prerequisite for renewal.
>German policy changed drastically in late 1938, after the annexation of [Sudetenland](https://en.wikipedia.org/wiki/Sudetenland) sealed the fate of Czechoslovakia, and Poland became Hitler's next target. In October 1938, German Foreign Minister [Joachim Ribbentrop](https://en.wikipedia.org/wiki/Joachim_Ribbentrop) presented Poland with the proposition of renewing the agreement in exchange for allowing the [Free City of Danzig](https://en.wikipedia.org/wiki/Free_City_of_Danzig) to be annexed by Germany and the construction of an [extraterritorial](https://en.wikipedia.org/wiki/Extraterritorial) motorway and railway through the [Polish Corridor](https://en.wikipedia.org/wiki/Polish_Corridor), with Germany accepting Poland's postwar borders.[[31]](https://en.wikipedia.org/wiki/German%E2%80%93Polish_declaration_of_non-aggression#cite_note-Wegener_Jul40-31) Since Poland refused, Hitler denounced the declaration unilaterally on 28 April 1939[[32]](https://en.wikipedia.org/wiki/German%E2%80%93Polish_declaration_of_non-aggression#cite_note-Brown2004_173-32) during an address before the [Reichstag](https://en.wikipedia.org/wiki/Reichstag_(Weimar_Republic)) while Germany renewed its territorial claims in Poland.

The decision should be named Operation Himmler/Konserve and should trigger a flavour events about "The Gleiwitz Incident", perhaps alongside all the other incidents and attacks staged. Which eventually gives Germany its casus belli on Poland.
https://en.wikipedia.org/wiki/Operation_Himmler 

>The Gleiwitz incident (German: Überfall auf den Sender Gleiwitz; Polish: Prowokacja gliwicka) was a false flag attack on the radio station Sender Gleiwitz in Gleiwitz (then Germany and now Gliwice, Poland) staged by Nazi Germany on the night of 31 August 1939. Along with some two dozen similar incidents, the attack was manufactured by Germany as a casus belli to justify the invasion of Poland. Prior to the invasion, Adolf Hitler gave a radio address condemning the acts and announcing German plans to attack Poland, which began the next morning.[1][2] Despite the German government using the attack as a justification to go to war with Poland, the Gleiwitz assailants were not Polish but were German SS officers wearing Polish uniforms. 

Basically, the Danzig or War stuff doesn't correspond to what actually unfolded on those moments and it's more accurate to change it to this, it also adds more flavour.
![image](https://user-images.githubusercontent.com/71605887/209584917-ed8e0290-0dd1-4e16-a4a3-713070a97970.png)

>Hitler cited the border incidents in a speech in the [Reichstag](https://en.wikipedia.org/wiki/Reichstag_(Weimar_Republic)) on the same day, with three of them called very serious, as justification for his invasion of Poland.[[14]](https://en.wikipedia.org/wiki/Gleiwitz_incident#cite_note-Hitler-14)

It could also be interesting to include a flavour event for Hitler's address to the Reichstag about these events.

>Hitler had told his generals on 22 August, "I will provide a propagandistic [casus belli](https://en.wikipedia.org/wiki/Casus_belli). Its credibility doesn't matter. The victor will not be asked whether he told the truth".[[6]](https://en.wikipedia.org/wiki/Gleiwitz_incident#cite_note-WirtzGordon-6)[[11]](https://en.wikipedia.org/wiki/Gleiwitz_incident#cite_note-Lightbody-11)

### Additional context

https://en.wikipedia.org/wiki/Fall_Weiss_(1939)
The Operation which was formulated for the Invasion of Poland, incase it can be inserted anywhere.

**Comment by SovietGengar2** [comment]
"Danzig or War"/The Gleiwitz Incident will be reworked along with many other Military Operations in a near Content Update. This suggestion will be taken into consideration.
