### ISSUE TITLE
FRA - Correct version of the vertical flag of France

### ISSUE THREAD

**Issue by Keetmanshoop** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#2]
### Hoi4 Version

Most recent

### DH Version

Most recent

### Description

In the teaser from the 28th of November, the French flag is not shown in the vertical version like the other flags. While a minor issue, I think it would be better to make a consistent use of vertical flags and change the French flag to this version: https://commons.m.wikimedia.org/wiki/File:Flag_of_France,_vertical.svg

### Reasoning

As can be seen in the image below, the flag of France does not follow the vertical proportions of the other flags.
![country_welcome](https://user-images.githubusercontent.com/74213291/209413063-bb5a0993-0730-47f4-bf75-9bb035c94244.png)

**Comment by markobekko** [comment]
The flag is correct, here an example at the "Arc de Triomphe"
![image](https://user-images.githubusercontent.com/63247018/209448454-ed68b60c-044d-4980-b639-f22ee58441c5.png)
