### ISSUE TITLE
<All> - <Railway Gun is a cube>

### ISSUE THREAD

**Issue by TheNicowars** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#24]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No

### Hoi4 Version

v1.12.7.8fc8 (b738) (S)

### DH Version

1.0

### Description

```bash
The railway guns don't have texture, and they appear as a cube when you zoom in enough.
```

### Screenshots/Video

![20221226135918_1](https://user-images.githubusercontent.com/121469296/209600391-433ad076-f7a0-47ad-bf88-ff8b8d06cfdf.jpg)

**Comment by SverigePranke** [comment]
It seems a file from vanilla was missing, it has been fixed. Thanks for reporting.
