### ISSUE TITLE
<Nation(s) Affected> - <Summary of In-game Crash>

### ISSUE THREAD

**Issue by Pawcio213** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#25]
### OS

Windows 10

### Any Expansions?

Together for Victory, Death or Dishonor, Waking the Tiger, Man the Guns, La Résistance, No Step Back, By Blood Alone

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

Newest so I guess 1.12.7

### DH Version

Steam v1.0 hotfix

### Other Mods

none

### Description

```bash
After performing Operation Sealion and capitulating UK game crashes during peace conference
```

### Reproduction steps

```bash
1 Win the war
2 Start peace conference
3 Do anything
4 Crash
```

### Logs

[error.log](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10307291/error.log)

### Savegame

[GER_1941_01_10_24.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10307295/GER_1941_01_10_24.zip)

**Comment by markobekko** [comment]
Does canada in your game exist?

**Comment by Pawcio213** [comment]
Dominion of Canada still exist
Something was supposed to happen to them?

**Comment by markobekko** [comment]
No, i was just asking because it could've been that they didn't exist for some reason, i think i fixed this problem, so next hotfix it shouldn't crash anymore
