### ISSUE TITLE
France - More Admirals

### ISSUE THREAD

**Issue by Imlitterallyhereforjustonemod** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#3]
### Hoi4 Version

1.12.7

### DH Version

1.0

### Description

```bash
Can France have more admirals?
```

### Reasoning

France has 3 admirals, but starts with more than 3. France definitely had more than 3 admirals that would qualify to lead fleets, so I think this is kind of a no-brianer.

**Comment by Imlitterallyhereforjustonemod** [comment]
I will also add on that France has no Field Marshals, that should definitely be fixed as well.

**Comment by ImperatorMaximo** [comment]
> 

France didn't had any active Field Marshals in the army in 1933 and only two of them were still alive in 1939, but didn't led any troops or army on the field at this point. However, I will probably had Gamelin as a "Field Marshal" because he was the généralissime des armées during the start of WW2.
