### ISSUE TITLE
CZE - Czechoslovakia gains Independence from Reichsprotektorat

### ISSUE THREAD

**Issue by Standislav** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#32]
### OS

Windows 11

### Any Expansions?

Death or Dishonor, By Blood Alone

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.12.7

### DH Version

1.0

### Description

```bash
Czechoslovakia gets Bohemia during the war I can't recall the date tho.
```

### Reproduction steps

```bash
1. play Germany as usual
2. In around 1940-41 Czechoslovakia gets Bohemia back out of nowhere
```

### Screenshots/Video

![obrazek](https://user-images.githubusercontent.com/112660047/209689164-6ddb6593-24ec-45fa-b801-26715d8db438.png)

**Comment by markobekko** [comment]
Could it be that they had very high resistance?

**Comment by Standislav** [comment]
Nope, they weren't at war with me when they declered independence which they would  also Reichsprotektorat has core on it so it's not possible btw I looked into my save files and in 1941 they do have the Bohemian province with cores but in 1943 it's owned by Czechoslovakia which doesn't have any other states

**Comment by Standislav** [comment]
Okay I found saves from 1942 and it seems that it has gained independence on July 15th

**Comment by SovietGengar2** [comment]
The UK has a focus in it's wartime tree that respawns CZE onto the map, in the Allies and at war with the Germans (Czechoslovak Government in Exile) It's supposed to not give control of any Czech state back to them. Is it possible that the UK did this focus and it is simply bugged?

**Comment by Standislav** [comment]
Yeah, that is probably what happaned. I tag switched into UK and they got this event after finishing their focus to do that.
![obrazek](https://user-images.githubusercontent.com/112660047/209806746-1e0fe41a-e504-48f2-a7fe-e2989cd942f3.png)
