### ISSUE TITLE
EHB/HCP/MEN/JAP/CHI - Wrong Formation Dates and Erroneous Events

### ISSUE THREAD

**Issue by HighMountainGuy** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#34]
### OS

Windows 10

### Any Expansions?

Together for Victory, Death or Dishonor, Waking the Tiger, Man the Guns, La Résistance, No Step Back

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

V1.12.7

### DH Version

V1.0

### Other Mods

X

### Description

```bash
(There's a lot to swallow here, and a lot is bugged so I'll try to explain them as concise as possible)

The East Hebei Autonomous Government was officially formed on the 25th of November, 1935. 
In the mod, it gets formed in October.

Another issue is that 4 days after East Hebei Gov's formation, an event appears which annexes the puppet regime (an unintended result of the original event being forgotten to be adjusted)

Hebei-Chahar Political Council shouldn't be formed this early either, it was formed on 18 December 1935

>The Hebei–Chahar Political Council, or Hebei-Chahar Political Commission (Chinese: 冀察政務委員會), was established at Beijing under Gen. Song Zheyuan, on 18th December 1935. 

The basic issues are, wrong tag formation dates, unintended annexation events, He-Umezu and Chin-Doihara Agreement events are incorrectly dated 
(He-Umezu concluded on the 10th of June, 1935) 
(Chin-Doihara concluded on the 27th of June 1935)
```

### Screenshots/Video

![image](https://user-images.githubusercontent.com/71605887/209689612-2714d973-5a3b-48f1-9fa5-8bfbabaa97f2.png)
![image](https://user-images.githubusercontent.com/71605887/209689637-4eb29dee-590d-4ab1-9600-2f767084e9af.png)
**East Hebei Gov. formed (wrong date)**

![image](https://user-images.githubusercontent.com/71605887/209689930-8881d430-2671-497d-a187-9176d0f2a024.png)
![image](https://user-images.githubusercontent.com/71605887/209689997-68a34639-746b-4dc8-8724-8d7eb3807e46.png)
**Incorrectly coded event**
![image](https://user-images.githubusercontent.com/71605887/209690118-ea592d28-335a-4ecb-9fd1-526e85408205.png)
Chin-Doihara Agreement fired on the wrong date, historically it happened in June of 1935
>The Chin–Doihara Agreement ([Chinese](https://en.wikipedia.org/wiki/Chinese_language): 秦土协定; [Japanese](https://en.wikipedia.org/wiki/Japanese_language): 土肥原・秦徳純協定, [romanized](https://en.wikipedia.org/wiki/Romanization_of_Japanese): Doihara-Qín Déchún) was a [treaty](https://en.wikipedia.org/wiki/Treaty) that resolved the [North Chahar Incident](https://en.wikipedia.org/wiki/North_Chahar_Incident) of 27 June 1935 between the [Empire of Japan](https://en.wikipedia.org/wiki/Empire_of_Japan) and [Republic of China](https://en.wikipedia.org/wiki/Republic_of_China_(1912%E2%80%931949)). The agreement was made between [Kwantung Army](https://en.wikipedia.org/wiki/Kwantung_Army) negotiator, [Kenji Doihara](https://en.wikipedia.org/wiki/Kenji_Doihara), representing Japan, and Deputy Commander of the [Kuomintang](https://en.wikipedia.org/wiki/Kuomintang) [29th Army](https://en.wikipedia.org/w/index.php?title=29th_Army_(China)&action=edit&redlink=1), General Qin Dechun (Chin Techun), representing China. It resulted in the [demilitarisation](https://en.wikipedia.org/wiki/Demilitarisation) of [Chahar](https://en.wikipedia.org/wiki/Chahar_(province)).

>As with the previous [He-Umezu Agreement](https://en.wikipedia.org/wiki/He-Umezu_Agreement) which gave Japan virtual control over the province of [Hebei](https://en.wikipedia.org/wiki/East_Hebei_Autonomous_Council), the Chin–Doihara Agreement was a first step in the establishment of Japanese control over [northern China](https://en.wikipedia.org/wiki/Hebei%E2%80%93Chahar_Political_Council) and [Inner Mongolia](https://en.wikipedia.org/wiki/Mengjiang). The Agreement resulted in considerable [anti-Japanese sentiment in China](https://en.wikipedia.org/wiki/Anti-Japanese_sentiment_in_China) and was one of the causes of the [December 9th Movement](https://en.wikipedia.org/wiki/December_9th_Movement) at the end of 1935.

### Logs

X

### Savegame

[JAP_1935_10_07_05.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10309407/JAP_1935_10_07_05.zip)
(October)
[JAP_1935_09_18_06.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10309581/JAP_1935_09_18_06.zip)
(September)

**Comment by markobekko** [comment]
The problem is that these border changes rely on border conflicts, so if they take too little then also the events will fire earlier

**Comment by HighMountainGuy** [comment]
But why would the formation of, lets say, the creation of Mengjiang and East Hebei, alongside the Hebei-Chahar Political Council be tied to border wars? That makes very little sense.

**Comment by HighMountainGuy** [comment]
Unless you mean the border wars check directly whether the requirements to form these nations are met, which is, understandable, but spaghetty in itself because it creates flow issues.

**Comment by HighMountainGuy** [comment]
But that doesn't answer why the He-Umezu newsevent didn't fire while the Chin-Doihara one did. I really think these things shouldn't be tied to the border wars themselves but instead fire on specific dates with the only checks being whether (x( states are controlled by (x) nations and (y) conditions are met.

The Suiyuan Campaign should also _only_ fire 5 months after the formation of the Mongol Military Government, currently it fires too fast

That's all I have to really say

**Comment by markobekko** [comment]
Basically once a border war is won/lost you get the event that progresses all the historical conflicts, that's why they could fire earlier/later than historical, i know it's not perfect but that's how it was designed

**Comment by HighMountainGuy** [comment]
Would it take too much effort to recode the event chains responsible?

**Comment by markobekko** [comment]
I fixed the Suiyuan Campaign firing too fast, as for coding it again yeah it would require quite some time since there are a lot of events, the only way i see this changed is if we remake Japan (which we'll probably do someday) since the design is very old and some parts are quite messy, but right we are only in 2 coders and we are really busy fixing the problems so there isn't much time to remake it, but maybe one day we will

**Comment by HighMountainGuy** [comment]
I guess that's something that can be deprioritized until 1.1/1.2 rolls around then, changing up a bunch of triggers and events to align with historical dates are really time consuming if what you're saying is true. Thanks for the explanation.
