### ISSUE TITLE
<Nation(s) Affected> - <Summary of In-game Crash>

### ISSUE THREAD

**Issue by BlitzoVictor** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#41]
### OS

Windows 7

### Any Expansions?

All of them

### Are you using Steam?

No i'm not

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.12.7

### DH Version

1.0

### Description

```bash
The game is crashing at 26 August 1938. I'm playing as Germany and just got the ultimatum at the czechs. After a while it keeps crashing at 26 August. I didn't get to test it with other countries or different situations.
```

### Reproduction steps

```bash
1. Go to '...'
2. Click on '...'
3. Select '...'
```

### Logs

[error.log](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10311041/error.log)

### Savegame

[save-games.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10311035/save-games.zip)

**Comment by Darijus11** [comment]
Can you tell me what version is shown in the bottom left screen when you are in the main menu? It is possible that you have an outdated version.

**Comment by Darijus11** [comment]
Can you tell me what version is shown in the bottom left screen when you are in the main menu? It is possible that you have an outdated version.

**Comment by BlitzoVictor** [comment]
> Can you tell me what version is shown in the bottom left screen when you are in the main menu? It is possible that you have an outdated version.

DH V1.0 Road to War

**Comment by Darijus11** [comment]
You are using an outdated version. This bug was fixed in a hotfix. What you need to do is subscribe and unsubscribe from the mod to get the update. I recommend you to wait 2ish hours for the new hotfix to arrive. Join our discord server for the announcement!

**Comment by BlitzoVictor** [comment]
Damn, ok então. Thank you so much for the help, i'm already in it.
