### ISSUE TITLE
Minor grammar/spelling issues

### ISSUE THREAD

**Issue by Kennelly1** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#49]
### Hoi4 Version

1.12.7

### DH Version (Current one is 1.0.0-hotfix-2)

1.0.0-hotfix-2

### Description

```bash
1. Tooltip should say "seize", not size in the second sentence
2. "compounds" should be "compund"
3. "bring" should be "bringing"
4. The sentence about America compunding problems for us makes no sense for America
5. The "such" in the second sentence makes no sense without a point of reference. Either delete it or add a reference point like "ideals as communism or fascism"
```

### Screenshots/Video

![Screenshot (1650)](https://user-images.githubusercontent.com/33550299/209831839-357807df-322f-41ff-b555-87d22b56cabc.png)
![Screenshot (1644)](https://user-images.githubusercontent.com/33550299/209832036-3e37d4e4-1762-4957-aca6-3fb3e46902bd.png)
![Screenshot (1645)](https://user-images.githubusercontent.com/33550299/209832142-c06ed9ac-67b4-445b-a1a7-3a4f3b933a22.png)
![Screenshot (1648)](https://user-images.githubusercontent.com/33550299/209832251-9824392a-7d86-493e-8cb1-448d15adfe67.png)
![Screenshot (1649)](https://user-images.githubusercontent.com/33550299/209832393-5c0c2623-f4f0-4053-9fe9-7869fa3b70b9.png)

**Comment by Darijus11** [comment]
Thank you for reporting this!
This will be fixed in the next patch!
