### ISSUE TITLE
<Nation(s) Affected> - <Summary of In-game Crash>

### ISSUE THREAD

**Issue by BAAKER** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#5]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.12.7

### DH Version

1.0

### Other Mods

DH Music sub-mod, Radio Moscow

### Description

```bash
Playing Soviet Union. On 18th September 1938 game crashes. I tried changing country on this date to see if this problem with Soviet Union, but it keeps crashing.
```

### Reproduction steps

```bash
Not sure what I should write here.
```

### Logs

The problem is that I'm playing using GeForce Now, so I can't provide any files.

### Savegame

The problem is that I'm playing using GeForce Now, so I can't provide any files.

**Comment by markobekko** [comment]
Fixed in the next hotfix
