### ISSUE TITLE
<ITA> - <National Spirits descriptions>

### ISSUE THREAD

**Issue by Kennelly1** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#53]
### OS

Windows 7

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

Yes i was

### Hoi4 Version

1.12.7

### DH Version (Current one is 1.0.0-hotfix-2)

1.0.0-hotfix-3

### Description

```bash
The descriptions for Italian spirits "High Command Incompetence" and "Overfunded Regia Marina" are switched.
```

### Screenshots/Video

![Screenshot (1660)](https://user-images.githubusercontent.com/33550299/209948540-193fc2ea-bf03-4616-b6a8-cd4b6ca0706d.png)
![Screenshot (1661)](https://user-images.githubusercontent.com/33550299/209948551-18cbd5eb-10a3-40fb-92f4-9811a95656f1.png)

**Comment by markobekko** [comment]
Typical italian incompetence smh
