### ISSUE TITLE
<Germany> - <Crash after Anschluss>

### ISSUE THREAD

**Issue by COOLMEN333** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#54]
### OS

Windows 10

### Any Expansions?

Together for Victory, Death or Dishonor, Waking the Tiger, Man the Guns, Battle For The Bosporus

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.12.7.8fc8(b738)

### DH Version (Current one is 1.0.0-hotfix-2)

1.0.0hotfix3

### Other Mods

none

### Description

```bash
after the message "Heim ins Reich" appears and I press it away, the game crashes.
```

### Reproduction steps

```bash
1. complete the focus "Heim ins Reich" with Germany
2. Click on the button "We wont let him deny the peoples will" below the message "Schuschnigg anounces a Refurendum"
3. Click on the button "Heim ins Reich" below the message "German Troops in Austria..."
4. It crashes
```

### Screenshots/Video

![Screenshot 2022-12-29 153328](https://user-images.githubusercontent.com/121623573/209968055-70914bd9-c266-4a8c-aa30-cb18d758e58b.png)
![Screenshot (1354)](https://user-images.githubusercontent.com/121623573/209968089-c4f9e1f2-8732-41a6-8965-d9407dc6019f.png)

### Logs

none

### Savegame

[Savegame Ironman Germany.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10319990/Savegame.Ironman.Germany.zip)

**Comment by Darijus11** [comment]
Can you clean up your game cache? This issue was fixed in the third hotfix.

**Comment by COOLMEN333** [comment]
Sorry, I dont know how. But if I start a new save, its there too. So I dont know... So could you give me a manual how to clean the game cache please?

**Comment by COOLMEN333** [comment]
Now I found it but it still crashes

**Comment by Darijus11** [comment]
Unsubscribe / Subscribe to the mod

**Comment by COOLMEN333** [comment]
I have already too

**Comment by SverigePranke** [comment]
Could you send the error log?

**Comment by COOLMEN333** [comment]
you mean that: https://community.cloudflare.steamstatic.com/public/javascript/webui/friends.js?v=RQGTBoXVY9FS&l=german&_cdn=cloudflare (14)

**Comment by SverigePranke** [comment]
No, go to your file explorer: documents/paradox interactive/hearts of iron iv/logs and then the error file

**Comment by COOLMEN333** [comment]
[error.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10320473/error.zip)
