### ISSUE TITLE
Italy possible bugs

### ISSUE THREAD

**Issue by pzgrV** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#56]
### OS

Windows 11

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.12.7

### DH Version (Current one is 1.0.0-hotfix-3)

1.00-3

### Other Mods

Darkest hour music

### Description

```bash
1) In the case of FIRST successful negotiations with IG FARBEN which ends up with gaining money, not paying, further progress is not possible. The game counts it as u haven`t had negotiations, cant take focus *establish SAIG* as well

2) Never was able to force King Zogu to submit, both options in the event are the same, looks like a bug
```

### Screenshots/Video

![изображение](https://user-images.githubusercontent.com/121650485/210028850-b20facc8-c6b5-4eba-b839-2871e9e5bad5.png)

![изображение](https://user-images.githubusercontent.com/121650485/210028878-3f9d0eb4-fc26-41fb-aa5e-04ee35d05b3c.png)

![изображение](https://user-images.githubusercontent.com/121650485/210029045-f696f110-e3ce-4af0-8002-76fded10a0d5.png)

### Savegame

[FARBEN+ZOGU.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10322879/FARBEN%2BZOGU.zip)

**Comment by SovietGengar2** [comment]
1) Fixed
2) Fixed
