### ISSUE TITLE
Australia - 1933 Western Australian secession referendum

### ISSUE THREAD

**Issue by tombricks** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#57]
### Hoi4 Version

1.11.7

### DH Version (Current one is 1.0.0-hotfix-3)

1.0.0-hotfix-3

### Description

```bash
Flavour news event recognising the results and aftermath of the 1933 Western Australian secession referendum and state election in which Western Australia voted to secede while also voting for an anti-secession party.
```

### Reasoning

Simple flavour event that shouldn't take long to add and would be an interesting piece of flavour for Australia.

**Comment by SovietGengar2** [comment]
I believe you and I have talked about this. I agree wholeheartedly, and will add such an event once we work on content for the Commonwealth.
