### ISSUE TITLE
<Soviet Union> - <Wave of militia focus doesnt check for if the soviets own Moscow>

### ISSUE THREAD

**Issue by WhyDoesCheeseExist** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#58]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.12.7

### DH Version (Current one is 1.0.0-hotfix-3)

1.0.0-hotfix-3

### Other Mods

DH music mod, player led peace conferences, Toolpack

### Description

```bash
The soviet focus "The defence of the union", which spawns militia units, doesn't check if the Soviets own Moscow, so when they do the focus and they don't own it, it is automatically transferred back into their hands, even if the Germans have already taken it 6 months ago.
```

### Screenshots/Video

![image](https://user-images.githubusercontent.com/63547428/210039868-0d451d0d-6d9b-44e5-9f13-2d825c22fe1f.png)
![image](https://user-images.githubusercontent.com/63547428/210039887-a6125a6e-eab0-4492-adfe-bdc6dea82883.png)
![image](https://user-images.githubusercontent.com/63547428/210039904-633d42c0-e80a-4b02-bef7-e51bcf8f7058.png)

### Savegame

Save file is too large.

**Comment by SovietGengar2** [comment]
Fixed, thank you for the report.
