### ISSUE TITLE
<Germany> - <Hindenburg Never Dies>

### ISSUE THREAD

**Issue by Furmon** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#59]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

Avalanche v1.12.8.31c5 (32be)

### DH Version (Current one is 1.0.0-hotfix-3)

1.0.0-hotfix-3

### Other Mods

None

### Description

```bash
Hindenburg is still alive in 1942, thus, preventing the German AI from completing its historical road to war. There is no current war. Playing as UK.
```

### Savegame

[ENG_1942_03_15_20.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10324753/ENG_1942_03_15_20.zip)

**Comment by markobekko** [comment]
Fixed in the next update
