### ISSUE TITLE
<France> - <Can't form the Cuirassie>

### ISSUE THREAD

**Issue by qweqweqwetyy** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#6]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.12.7

### DH Version

1.0

### Other Mods

Songs of Our Darkest Hour - Official Music Submod

### Description

```bash
Game crashed when checked on "Form 1e division Cuirassie"
```

### Reproduction steps

```bash
1. Go to 'event and decision'
2. Click on 'Army motorization'
3. Select 'Form 1e division Cuirassie'
```

### Screenshots/Video

![Screenshot 2022-12-26 210923](https://user-images.githubusercontent.com/85399236/209553342-d05480d9-df7a-4645-9c27-f9773b4ba0d8.png)

### Logs

[error.log](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10303601/error.log)

### Savegame

[FRA_1938_11_14_05.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10303599/FRA_1938_11_14_05.zip)

**Comment by markobekko** [comment]
Already fixed, thank you
