### ISSUE TITLE
US, Turkey, France and UK - Buggy texture hovering and flickering over some cities

### ISSUE THREAD

**Issue by GoldenTemple2002** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#61]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.12.7

### DH Version (Current one is 1.0.0-hotfix-3)

1.0.0-hotfix-3

### Description

```bash
A white box appears and flickers over Paris, London, Istanbul and Washington D.C. Especially bad over D.C.
```

### Reproduction steps

```bash
I just started a new game as Germany, simply looked at these cities that have a buggy white texture hovering over them.
```

### Screenshots/Video

![20221231210632_1](https://user-images.githubusercontent.com/102491472/210155687-b134b21b-862d-4cb5-b55e-90a1d54ca879.jpg)
![20221231211407_1](https://user-images.githubusercontent.com/102491472/210155706-32c37241-11e6-4995-b1fb-4ba15ee98c5d.jpg)

**Comment by markobekko** [comment]
We can't do anything about this it's a paradox issue, try switiching to another version of directx or to opengl from the launcher.

**Comment by GoldenTemple2002** [comment]
Can confirm that switching to DirectX 9 solves this issue.
