### ISSUE TITLE
<Germany> - <German guy never dies>

### ISSUE THREAD

**Issue by Nyroh7** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#62]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

the most recent

### DH Version (Current one is 1.0.0-hotfix-3)

1.0.0-hotfix-3

### Other Mods

player led peace conference/ better preset colors/ colorise your country/ toolpack/ no autonomy from trade

### Description

```bash
So for hitler to continue the focus tree he needs the other head of state to dies but the AI Germany never killed him (I was playing France)
```

**Comment by scorobetele** [comment]
Got the same problem. Hindenburg doesn't die when he's supposed to.

**Comment by markobekko** [comment]
Update to the newest version
