### ISSUE TITLE
<Germany> - <Missing General Portraits>

### ISSUE THREAD

**Issue by COOLMEN333** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#64]
### OS

Windows 10

### Any Expansions?

Together for Victory, Death or Dishonor, Waking the Tiger, Man the Guns, Battle For The Bosporus

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

1.12.7.8fc8(b738)

### DH Version (Current one is 1.0.1)

1.0.1

### Other Mods

none

### Description

```bash
The portraits of the following Generals are Missing: Erich von Mannstein, Fedor von Bock, Erwin von Witzleben, Maximilian von Weichs, Hasso von Mannteufel, Alexander von Falkenhausen (he has the false spelling by the way in the mod).
```

### Screenshots/Video

![Screenshot 2023-01-01 135329](https://user-images.githubusercontent.com/121623573/210171275-cf498508-c0e0-4083-a0f7-bcd53f91386e.png)

### Logs

none

### Savegame

not necessary

**Comment by SverigePranke** [comment]
There was a small typo in the names of the portraits, the issue has been fixed. Thanks for reporting!
