### ISSUE TITLE
GER - Positive Christianity Bug

### ISSUE THREAD

**Issue by HighMountainGuy** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#68]
### OS

Windows 10

### Any Expansions?

Together for Victory, Death or Dishonor, Waking the Tiger, Man the Guns, La Résistance, No Step Back

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

V1.12.7

### DH Version (Current one is 1.0.1)

V1.0.1

### Other Mods

X

### Description

```bash
The irreligious variable in the Positive Christianity mechanic can become a negative value
```

### Screenshots/Video

![image](https://user-images.githubusercontent.com/71605887/210260411-5ea41187-79a4-45db-b747-1925949c8b04.png)

### Logs

X

### Savegame

X

**Comment by SverigePranke** [comment]
Fixed
