### ISSUE TITLE
GER - Positive Christianity Issue #2

### ISSUE THREAD

**Issue by HighMountainGuy** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#69]
### OS

Windows 10

### Any Expansions?

Together for Victory, Death or Dishonor, Waking the Tiger, Man the Guns, La Résistance, No Step Back

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

V1.12.7

### DH Version (Current one is 1.0.1)

V1.0.1

### Other Mods

X

### Description

```bash
Something should be done to make the transformation of catholics and protestants to positive christianity far harder and slow, I managed to speedrun "Deutsches Christentum" by late 1936.
```

### Screenshots/Video

![image](https://user-images.githubusercontent.com/71605887/210263681-b97f398c-d609-4dbf-83c4-d3ee58818b57.png)
![image](https://user-images.githubusercontent.com/71605887/210263708-24b9a378-620d-483b-9896-b3e8d09152d5.png)

### Logs

X

### Savegame

X

**Comment by Lucas-Brault** [comment]
I agree on this, Converting an entire nation with 50+ Million People will be incredibly difficult and realistically take more than 30 years. Making it Über Realistic on the other hand would be incredibly stupid as it wouldn't be fun having to wait until the 1950s until you fully convert your nation into a different religion. I'd say that full conversion of the Nation should take place somewhere around 1939-40, making those sweet Stability and War Support bonuses ever so useful as you are bombarded with negative modifiers from being at War.
