### ISSUE TITLE
<Japan> - <Yen block bugs+ peace with china bugs+suggestions>

### ISSUE THREAD

**Issue by pzgrV** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#72]
### OS

Windows 11

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

Nope

### Hoi4 Version

last (blood alone)

### DH Version (Current one is 1.0.1)

1.0.1 h3

### Description

```bash
1)Seems like Yen block should give a bonus to money income due to its description *screenshot 1* should provide +33% impact on income, but it's not providing *screenshot 2*.  This makes u able to survive only with free market policy(even with death+taxes), though already have conquered China + weird not to have Corporatism considering Dzaibatsu in reality

2.1) After the capitulation of China Liangguang Clique for some reason stays in the "Second United Front" together with China, but being my puppet at the same time, they also have a weird province nearby Moscow
*Screenshots *3*4*
2.2) Same applies to Shanxi : Screenshot 6

3)Was never(around 10 tries) able to hold a Karuizawa COnference, though had Konoe as a prime minister *screenshot 5*

4)Invitation of Thailand(by Japan) is not working, Thailand receives a special bonus for *+10 War Desire* and thats it

5)As a result of issues 2.1 and 2.2 i had to start a war with Shanxi and Liangguang appeared to be at war with itself *screenshot 7*
which breaks the game, cuz this war is endless( see P.S.)

6) Wasn`t able to figure out how to get Tojo Hideki, in war with allies for like a year (1943-1944, ongoing) *savefile TOJO*, screenshot 8

7) Income modifier from the minister also not counting in the end of the day |*screenshot 9*

Suggestions:
1)Weird Peace conference for China => troops just conquered the very northwest of China, stay next to the soviet borders but then for some reason have to go all the way back due to enforced peace, just to return in a couple of months with the next war}

2)A Focus tree for war with the Soviets, especially after success in China. 

3)Logic of having various ministers if u actually cant pick them, isn`t clear for me, mb its bug.  *scrn10-11*
```

P.S. Found out that Issue 2.1+2.2. happen if during the second Japanese-Chinese war Japan calls to arms New Guangxi Clique, Clique and the Republic of China will have a peace agreement which brings to this issue.  Savefile *bug* (u first have to force Rep of China to surrender by capturing territory near the New Guangxi Clique

P.S.S. Is it really a feature that rocket artillery cant be motorized and has to reduce the speed of the division down to 0.5?

### Screenshots/Video

1) ![изображение](https://user-images.githubusercontent.com/121650485/210277691-aa8abcbc-86ed-4024-b241-b862dc6916b0.png)

2) ![изображение](https://user-images.githubusercontent.com/121650485/210277743-c0b71183-47e7-4ac1-8834-af1e2c3bfd1c.png)
3) ![изображение](https://user-images.githubusercontent.com/121650485/210277973-d7ce67b1-c1c8-430d-9f91-ee8b80a21827.png)

4) ![изображение](https://user-images.githubusercontent.com/121650485/210277984-d07f0ea2-5ede-4126-b1c0-147b567285e2.png)

5) ![изображение](https://user-images.githubusercontent.com/121650485/210278006-c3a11d9d-bda8-492f-8bd4-31a7e7fc10d4.png)

6) ![изображение](https://user-images.githubusercontent.com/121650485/210278621-d71c5503-b7d8-4442-89ce-fe0602b79ab6.png)

7) 
![изображение](https://user-images.githubusercontent.com/121650485/210280679-2803416a-e740-4c34-936d-cd88a50b5dc5.png)

8) 
![изображение](https://user-images.githubusercontent.com/121650485/210289202-abdf0975-dd49-4f19-ba7d-41b4bdf62648.png)

9)
![изображение](https://user-images.githubusercontent.com/121650485/210397972-9b0c3546-bc27-48f3-a416-a6de1d789a4f.png)

10)
![изображение](https://user-images.githubusercontent.com/121650485/210398333-37cc1033-cdf9-4375-b67e-bca5674f6a39.png)

11)
![изображение](https://user-images.githubusercontent.com/121650485/210398454-bf573038-5bfe-4a44-a9b6-0df255f526ce.png)

### Savegame

[autosave.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10333488/autosave.zip) -1942 or 1943 for chinese stuff

[Tojo.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10333932/Tojo.zip) - cant get TOJO 1944

**Comment by markobekko** [comment]
Can you tell me how is the high command guy called in the 10th/11th screenshot?

**Comment by markobekko** [comment]
As for the 7th point, the minister does give money income, the problem is there is a bug that paradox didn't fix yet (and who knows if they'll ever fix it) so that we can't showcase that the money has increased because of an "idea" but it's put in the "others" category

**Comment by pzgrV** [comment]
> Can you tell me how is the high command guy called in the 10th/11th screenshot?

Not sure I got what you mean. On the 10th and 11th screenshots, I wanted to demonstrate that among various ministers u actually can choose only between a few, cuz the game thinks that the player already appointed a minister with such a trait, but this is bs.
IMHO for some reason description of the *class* *eg: silent workhorse, prince of terror. crime fighter etc) arent managed properly.

**Comment by markobekko** [comment]
I mean that probably the high command guy you appointed is bugged, so i wanted to know the name so i can see if it's his problem or something else

**Comment by pzgrV** [comment]
The guy on the left(second line, under Hirohito) is Tojo Hideki (in glasses).

**Comment by markobekko** [comment]
![immagine](https://user-images.githubusercontent.com/63247018/212326556-b99a6c6f-d78e-4eff-af1c-bf9290507936.png)
I mean this guy

**Comment by pzgrV** [comment]
can't really say. on the last save that I have that`s Imamura 
![изображение](https://user-images.githubusercontent.com/121650485/212683697-b81836dc-f6a3-4edf-804b-883772eabb84.png)
