### ISSUE TITLE
German Reich - Plane Experience Level Icon staying the same

### ISSUE THREAD

**Issue by Lucas-Brault** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#74]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

Avalanche V1.12.7.8FC8

### DH Version (Current one is 1.0.1)

V1.0.1

### Other Mods

Coloured Airforce Updated, Darkest Hour, More Division Icons Updated, Strategic View Adjustments, Tool Pack | 2022 Edition, Uncensored German Abwhehr Emblem, Vine Boom War Sound Effect.

### Description

```bash
Something that is throwing me off quite a bit is the Experience Level of my planes, they have the same Icon as untrained Planes. I am guessing the Code can't find it's way to the other Icons, but it's not my expertise to fix this problem. I appreciate the developers for creating this wonderful Mod and bugs happen.
```

### Screenshots/Video

![image](https://user-images.githubusercontent.com/122098852/211021511-10b46146-64f2-4e67-a4df-02adcc6a2680.png)

**Comment by markobekko** [comment]
It's not a bug, there are more levels than vanilla
![immagine](https://user-images.githubusercontent.com/63247018/211104982-4810226c-bbd4-4579-8aab-54b166afdbc6.png)
![immagine](https://user-images.githubusercontent.com/63247018/211105034-6d8b5e5c-ffee-4aa2-8b82-305b5db8e134.png)
As you can see in the 2° screenshot the level of the unit is 6, but it's only the 1° regular level
