### ISSUE TITLE
All Nations affected / Cant open Research 

### ISSUE THREAD

**Issue by xXJNHLXx** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#80]
### OS

Windows 10

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

Avalanche v1.12.7.8fc8 (b738)

### DH Version (Current one is 1.0.1)

1.0.1 and 1.0.2

### Other Mods

none

### Description

```bash
Hello dear Dev team this is my first issue with your mod. The first time i played it, is along time ago but since your new 1.0 release i started playing again and discoverd that i cant research anything. Do you know how i can fix it? Its the only mod in which this happens to me. If I would open the "research tab using the "w" key i see the place were i can see the list of my research slots but when i press on them i see the menu openning and closing istantly. 

I would be pleased to hear from you. can help me? 

Wish you a happy day.
```

**Comment by Darijus11** [comment]
Open console and type in "reloadtechnologies". Hope this helps

**Comment by xXJNHLXx** [comment]
Thanks for the quick awnser but i sadly didnt work

**Comment by markobekko** [comment]
Try resubscribing to the mod, if this also doesn't work then reinstall hoi4

**Comment by xXJNHLXx** [comment]
i tried both already and it didnt change anything

**Comment by markobekko** [comment]
This looks really a problem on your end, since no one else reported this, try going to the documents folder and deleting the "Hearts of Iron IV" folder, then reinstall hoi4 and then resubscribe to the mod

**Comment by xXJNHLXx** [comment]
well i tried it tree times now but it is still not working
