### ISSUE TITLE
Soviet union: five year plans decisions should be extended

### ISSUE THREAD

**Issue by Zaithon141** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#88]
### Hoi4 Version

Avalanche 1.12.9.d0ab (13d8)

### DH Version (Current one is 1.0.2-hotfix-1)

V1.0.2HOTFIX1

### Description

```bash
Five year plan decisions should take longer to complete or there should be more decisions
```

### Reasoning

AI soviet union doesn't finish a majority of their 2nd five year plan focuses as they complete it by 1934 
![image](https://user-images.githubusercontent.com/82981723/215248350-c03b126f-fc7b-4bee-aa10-6f2ef789f300.png)
![image](https://user-images.githubusercontent.com/82981723/215248356-a77f9181-2142-4658-8be0-16eddaeba40f.png)
![image](https://user-images.githubusercontent.com/82981723/215248364-82f6ef9f-ffbb-43e9-a6ed-e0145b8ba67e.png)

**Comment by killkieran** [comment]
agree or at least allow for the big second baku vs synthetic oil choices to remain available as my tree for the third fave year is stuck after fragmentation decision because i got neither in time...
