### ISSUE TITLE
Italy is too strong

### ISSUE THREAD

**Issue by Zaithon141** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#89]
### OS

Windows 11

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

Avalanche 1.12.9.d0ab (13d8)

### DH Version (Current one is 1.0.2-hotfix-1)

V1.0.2HOTFIX1

### Other Mods

modifier icons, alternative air base and naval base icons, coloured interface compact ironman

### Description

```bash
Italy's ai can have 750k fully equipped soldiers by the time they invaded Ethiopia while Germany ai struggled to output 350k by 1936 and even failed their rearmament programs
```

### Screenshots/Video

![image](https://user-images.githubusercontent.com/82981723/215250132-5f8d962b-cbc9-4866-83e1-ede525f1bdee.png)
![image](https://user-images.githubusercontent.com/82981723/215250149-be2a45da-b517-4275-99d0-15b0fcf146b2.png)
![image](https://user-images.githubusercontent.com/82981723/215250161-c632f9d4-6d25-42de-8233-0620a14a3504.png)

### Savegame

[ITA_1935_11_12_05.zip](https://github.com/Darkest-Hour-Hoi4/Darkest-Hour-Issues/files/10526070/ITA_1935_11_12_05.zip)

**Comment by SverigePranke** [comment]
Seems more like Germany is too weak

**Comment by Zaithon141** [comment]
hmm maybe

**Comment by Zaithon141** [comment]
last game germany did rhineland in may since they didn't have enough men in the field and they were a bit short on artillery and something else
