### ISSUE TITLE
<Nation(s) Affected> - <Summary of Bug>

### ISSUE THREAD

**Issue by CT3243** [Darkest-Hour-Hoi4/Darkest-Hour-Issues#99]
### OS

Windows 7

### Any Expansions?

All of them

### Are you using Steam?

Yes i am

### Were you playing in multiplayer?

No i wasn't

### Hoi4 Version

AVALANCHE V1.12.7.8FC8 (DD7A) (S)

### DH Version (Current one is 1.0.2-hotfix-1)

DH V1.0.2 HOTFIX 1

### Other Mods

None

### Description

```bash
The factory model appears as an obnoxious white square, I believe it’s a graphical glitch.
```

### Screenshots/Video

https://user-images.githubusercontent.com/123595602/218336307-68463bee-59df-405f-9dfa-be950717718a.MOV

**Comment by Darijus11** [comment]
Lower your DirectX version in the Paradox launcher. This is Paradox's glitch that we cannot fix unfortunately...
